### ISSUE TITLE
Playdate version does not work on device itself, but the fix is easy

### ISSUE THREAD

**Issue by joyrider3774** [abagames/crisp-game-lib-portable#1]
Hi,

I own a playdate and stumbled upon this repo and tried it out on my playdate (the actual device), but it was not displaying anything at all on the device itself but it did display things in the simulator. It turns out the fix is really easy you see the update function should return `1` not `0` or it does not update anything on the screen on the device, so changing this line https://github.com/abagames/crisp-game-lib-portable/blob/main/src/cglpPlaydate/src/cglpPlaydate.c#L155 from `return 0` to `return 1` fixed the issue

**Comment by abagames** [comment]
Thank you for testing on the actual device! I will apply the fix immediately.
