### ISSUE TITLE
Added ESPboy support

### ISSUE THREAD

**Issue by ESPboy-edu** [abagames/crisp-game-lib-portable#3]
www.espboy.com
https://github.com/ESPboy-edu/ESPboy_crisp-game-lib-portable/tree/main/cglpESPboy

**Comment by abagames** [comment]
Thank you! I'll add the link to the README.

**Comment by ESPboy-edu** [comment]
Yes, thank you.

Here is video https://youtu.be/sKtzbp46qn8?si=Q1bVrn43ns6d3zuS

In the ESPboy version I had to remove the character caching in the library file "cglp.c" function "void drawCharacter(...)" and lower some value parameters, e.g.

#define MAX_SOUND_EFFECT_NOTE_LENGTH 16
#define MAX_HIT_BOX_COUNT 128
#define MAX_DRAWING_HIT_BOXES_COUNT 32
#define MAX_SCORE_BOARD_COUNT 8
#define MAX_RECORDED_INPUT_COUNT 100

and also move some static data to PROGMEM both in the library itself and in the games

 because there was too low MCU RAM memory
However, drawing without caching is fast enough.

Is there any possibility of automatic conversion of games from JS crisp-game-lib?

**Comment by abagames** [comment]
The JavaScript language specification is too rich for automatic conversion to C. To make automatic conversion possible, it may be necessary to limit the JavaScript functionality available in JS crisp-game-lib to a subset.

**Comment by ESPboy-edu** [comment]
_it may be necessary to limit the JavaScript functionality available in JS crisp-game-lib to a subset._
definitely a good idea to make wider wonderful numerous CGL (crisp-game-lib) games representation and available to more users )
